### ISSUE TITLE
Python: itertools.imap has no len

### ISSUE THREAD

**Issue by just-paja** [debops/ansible-slapd#36]
Hi, 

I just wanted to try this on virtual machine, but I can't get over this python error. How can a TypeError happen?

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py", line 324, in <module>
    main()
  File "/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py", line 170, in main
    LdapAttr(module).main()
  File "/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py", line 223, in main
    modlist = self.handle_exact()
  File "/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py", line 266, in handle_exact
    elif len(self.values) == 0:
TypeError: object of type 'itertools.imap' has no len()

failed: [cloud] (item={'key': u'olcRootPW', 'value': u'{SSHA}uO+uHjdfay2st72uPOFhjFV6TkK2/FbG'}) => {
    "failed": true, 
    "invocation": {
        "module_name": "ldap_attr"
    }, 
    "item": {
        "key": "olcRootPW", 
        "value": "{SSHA}uO+uHjdfay2st72uPOFhjFV6TkK2/FbG"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py\", line 324, in <module>\n    main()\n  File \"/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py\", line 170, in main\n    LdapAttr(module).main()\n  File \"/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py\", line 223, in main\n    modlist = self.handle_exact()\n  File \"/tmp/ansible_6GfiSl/ansible_module_ldap_attr.py\", line 266, in handle_exact\n    elif len(self.values) == 0:\nTypeError: object of type 'itertools.imap' has no len()\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

```
This is from the virtual machine I was installing to.
```
$ python --version
Python 2.7.12
$ pip freeze
httplib2==0.9.1
pycurl==7.43.0
python-apt==1.1.0b1
python-ldap==2.4.22
ranger==1.7.1
```

**Comment by drybjed** [comment]
The `ldap_attr` and `ldap_entry` modules included in the `debops-playbooks` repository have been updated to new versions which are due to be merged into Ansible modules repository. Can you update them and check if the issue still shows up?
